# Site settings
title: Full-Stack Follies
header-img: img/home-bg.png
email: jelolearns@gmail.com
copyright_name: jelocodes
description: > # this means to ignore newlines until "baseurl:"
  A personal blog about learning full-stack web development.
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: jelotweets
github_username:  jelocodes
learn_profile: jelocodes
email_username: jelolearns@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
